
import ResponsiveAppBar from '@/components/AppBar'
import '@fontsource/roboto/400.css'
import { Box } from '@mui/material'

import './globals.css'

export const metadata = {
  title: 'Dendi Z',
  description: 'Generated by Next.js'
}

export default function RootLayout ({
  children
}: {
  children: React.ReactNode
}) {
  

  return (
    <html lang='en'>
      <body>
        <ResponsiveAppBar />

        <Box
          className='main-container'
          sx={{
            paddingLeft: 4,
            paddingRight: 4,
            paddingTop: '60px',
            justifySelf: 'center',
            maxWidth: '760px',
            minHeight:'100vh'
          }}
        >

          {children}
        </Box>
        <footer className='footer'>
          <p>@ 2024 Dendi.z eeeegou.</p>
        </footer>
      </body>
    </html>
  )
}
