/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: 16Bit_Gamer_2010 (https://sketchfab.com/maksFanGamer90)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/super-mario-bros-1-1-all-stars-3d-77f5672f40bb400688ec057390ed8aa6
Title: Super Mario Bros 1-1 ALL-Stars 3D
*/

import { useGLTF } from '@react-three/drei'
import React from 'react'

export function Model(props) {
  const { nodes, materials } = useGLTF('/super_mario_bros_1-1_all-stars_3d.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_5.geometry}
        material={materials.material_0}
        position={[0.06, 1.69, 0]}
      />
      <mesh geometry={nodes.Object_8.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_17.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_19.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_21.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_24.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_26.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_28.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_30.geometry} material={materials.material_0} />
      <mesh
        geometry={nodes.Object_33.geometry}
        material={materials.material_0}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_35.geometry}
        material={materials.material_0}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_37.geometry}
        material={materials.material_0}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_39.geometry}
        material={materials.material_0}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('/assets/super_mario_bros_1-1_all-stars_3d.glb')
